services:

  node_api:
    build:
      context: ./node-api
    ports:
      - 3000:3000
    container_name: node_api
    volumes:
      - ./node-api:/app
      - /app/node_modules
    command: node app.js
    networks:
      - app-network

  flask_api:
    build: ./python-api
    container_name: flask_api
    ports:
      - 5000:5000
    volumes:
      - ./python-api:/app
    command: python app.py
    depends_on:
      - dbmysql
    networks:
      - app-network

  dbmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 932545
      MYSQL_DATABASE: devopsaula8
    ports:
      - 3307:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge