services:
  flask_api:
    build: ./python-api
    container_name: python_api
    ports:
      - 5000:5000
    volumes:
      - ./python-api:/app
    command: python app.py

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db  
    environment:
      MYSQL_USER: root
      MYSQL_HOST: joao_db
      MYSQL_ROOT_PASSWORD: 932545
      MYSQL_DATABASE: devopsaula8
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge